### ISSUE TITLE
Incompatibility with Python 3.7 because of async keyword argument

### ISSUE THREAD

**Issue by ramdeif** [berkerpeksag/astor#115] opened 2018-07-05 15:55 UTC
Hello!

In Python 3.7 `async` becomes a keyword, and so It is not a valid keyword argument now. I think It is a good idea to rename this keyword argument in some functions? For example, You can use `async_` instead.
Now Astor doesn't work in Python 3.7 throwing `SyntaxError`.
Thank you!

**Comment by berkerpeksag** [comment] 2018-07-05 16:18
Thanks for the report! This has already been fixed in master, but I've been waiting for some PRs since the last week. I guess I should just release master as-is. You can subscribe to #111 for the status of 0.7.

Closing this as a duplicate of #86.

**Closed by berkerpeksag** 2018-07-05 16:18 UTC

**Comment by berkerpeksag** [comment] 2018-07-05 18:02
0.7 is now up! https://pypi.org/project/astor/0.7.0/
