### ISSUE TITLE
0.8.1: test suite i sfailing

### ISSUE THREAD

**Issue by kloczek** [berkerpeksag/astor#193] opened 2021-01-20 02:17 UTC
```
+ cd astor-0.8.1
+ /usr/bin/python3 -m pytest -v
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.3, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/tkloczko/rpmbuild/BUILD/astor-0.8.1/.hypothesis/examples')
rootdir: /home/tkloczko/rpmbuild/BUILD/astor-0.8.1
plugins: flaky-3.6.1, forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, cov-2.10.1, xdist-2.2.0, asyncio-0.14.0, hypothesis-6.0.2, expect-1.1.0
collected 55 items

tests/test_code_gen.py::CodegenTestCase::test_annassign PASSED                                                                                                       [  1%]
tests/test_code_gen.py::CodegenTestCase::test_arguments PASSED                                                                                                       [  3%]
tests/test_code_gen.py::CodegenTestCase::test_assignment_expr PASSED                                                                                                 [  5%]
tests/test_code_gen.py::CodegenTestCase::test_async_comprehension PASSED                                                                                             [  7%]
tests/test_code_gen.py::CodegenTestCase::test_async_def_with_for PASSED                                                                                              [  9%]
tests/test_code_gen.py::CodegenTestCase::test_attribute PASSED                                                                                                       [ 10%]
tests/test_code_gen.py::CodegenTestCase::test_class_definition_with_starbases_and_kwargs PASSED                                                                      [ 12%]
tests/test_code_gen.py::CodegenTestCase::test_compile_types PASSED                                                                                                   [ 14%]
tests/test_code_gen.py::CodegenTestCase::test_complex PASSED                                                                                                         [ 16%]
tests/test_code_gen.py::CodegenTestCase::test_comprehension PASSED                                                                                                   [ 18%]
tests/test_code_gen.py::CodegenTestCase::test_constant_nodes PASSED                                                                                                  [ 20%]
tests/test_code_gen.py::CodegenTestCase::test_del_statement PASSED                                                                                                   [ 21%]
tests/test_code_gen.py::CodegenTestCase::test_deprecated_constant_nodes PASSED                                                                                       [ 23%]
tests/test_code_gen.py::CodegenTestCase::test_deprecated_constants_as_name SKIPPED (ast.Name used for True, False, None until Python 3.4)                            [ 25%]
tests/test_code_gen.py::CodegenTestCase::test_deprecated_name_constants PASSED                                                                                       [ 27%]
tests/test_code_gen.py::CodegenTestCase::test_dictionary_literals PASSED                                                                                             [ 29%]
tests/test_code_gen.py::CodegenTestCase::test_docstring_class PASSED                                                                                                 [ 30%]
tests/test_code_gen.py::CodegenTestCase::test_docstring_function PASSED                                                                                              [ 32%]
tests/test_code_gen.py::CodegenTestCase::test_docstring_method PASSED                                                                                                [ 34%]
tests/test_code_gen.py::CodegenTestCase::test_docstring_module PASSED                                                                                                [ 36%]
tests/test_code_gen.py::CodegenTestCase::test_double_await PASSED                                                                                                    [ 38%]
tests/test_code_gen.py::CodegenTestCase::test_elif PASSED                                                                                                            [ 40%]
tests/test_code_gen.py::CodegenTestCase::test_empty_iterable_literals PASSED                                                                                         [ 41%]
tests/test_code_gen.py::CodegenTestCase::test_fstring_debugging PASSED                                                                                               [ 43%]
tests/test_code_gen.py::CodegenTestCase::test_fstring_escaped_braces PASSED                                                                                          [ 45%]
tests/test_code_gen.py::CodegenTestCase::test_fstring_trailing_newline PASSED                                                                                        [ 47%]
tests/test_code_gen.py::CodegenTestCase::test_fstrings PASSED                                                                                                        [ 49%]
tests/test_code_gen.py::CodegenTestCase::test_huge_int PASSED                                                                                                        [ 50%]
tests/test_code_gen.py::CodegenTestCase::test_imports PASSED                                                                                                         [ 52%]
tests/test_code_gen.py::CodegenTestCase::test_inf PASSED                                                                                                             [ 54%]
tests/test_code_gen.py::CodegenTestCase::test_matrix_multiplication PASSED                                                                                           [ 56%]
tests/test_code_gen.py::CodegenTestCase::test_multiple_call_unpackings PASSED                                                                                        [ 58%]
tests/test_code_gen.py::CodegenTestCase::test_nan PASSED                                                                                                             [ 60%]
tests/test_code_gen.py::CodegenTestCase::test_non_string_leakage PASSED                                                                                              [ 61%]
tests/test_code_gen.py::CodegenTestCase::test_output_formatting PASSED                                                                                               [ 63%]
tests/test_code_gen.py::CodegenTestCase::test_pass_arguments_node PASSED                                                                                             [ 65%]
tests/test_code_gen.py::CodegenTestCase::test_positional_only_arguments PASSED                                                                                       [ 67%]
tests/test_code_gen.py::CodegenTestCase::test_pow PASSED                                                                                                             [ 69%]
tests/test_code_gen.py::CodegenTestCase::test_right_hand_side_dictionary_unpacking PASSED                                                                            [ 70%]
tests/test_code_gen.py::CodegenTestCase::test_slicing PASSED                                                                                                         [ 72%]
tests/test_code_gen.py::CodegenTestCase::test_try_expect PASSED                                                                                                      [ 74%]
tests/test_code_gen.py::CodegenTestCase::test_tuple_corner_cases PASSED                                                                                              [ 76%]
tests/test_code_gen.py::CodegenTestCase::test_unary PASSED                                                                                                           [ 78%]
tests/test_code_gen.py::CodegenTestCase::test_unicode_literals PASSED                                                                                                [ 80%]
tests/test_code_gen.py::CodegenTestCase::test_with PASSED                                                                                                            [ 81%]
tests/test_code_gen.py::CodegenTestCase::test_yield PASSED                                                                                                           [ 83%]
tests/test_misc.py::GetSymbolTestCase::test_get_mat_mult PASSED                                                                                                      [ 85%]
tests/test_misc.py::PublicAPITestCase::test_aliases PASSED                                                                                                           [ 87%]
tests/test_misc.py::PublicAPITestCase::test_codegen_as_submodule PASSED                                                                                              [ 89%]
tests/test_misc.py::PublicAPITestCase::test_codegen_from_root PASSED                                                                                                 [ 90%]
tests/test_misc.py::PublicAPITestCase::test_to_source_invalid_customize_generator PASSED                                                                             [ 92%]
tests/test_misc.py::FastCompareTestCase::test_fast_compare PASSED                                                                                                    [ 94%]
tests/test_misc.py::TreeWalkTestCase::test_auto_generated_attributes PASSED                                                                                          [ 96%]
tests/test_misc.py::SourceReprTestCase::test_split_lines_unicode_support SKIPPED (only applies to Python 2)                                                          [ 98%]
tests/test_rtrip.py::RtripTestCase::test_convert_stdlib FAILED                                                                                                       [100%]

================================================================================= FAILURES =================================================================================
____________________________________________________________________ RtripTestCase.test_convert_stdlib _____________________________________________________________________

self = <tests.test_rtrip.RtripTestCase testMethod=test_convert_stdlib>

    def test_convert_stdlib(self):
        srcdir = os.path.dirname(os.__file__)
        result = astor.rtrip.convert(srcdir)
>       self.assertEqual(result, [])
E       AssertionError: Lists differ: ['/usr/lib64/python3.8/site-packages/panda[508 chars].py'] != []
E
E       First list contains 8 additional elements.
E       First extra element 0:
E       '/usr/lib64/python3.8/site-packages/pandas/io/formats/html.py'
E
E       + []
E       - ['/usr/lib64/python3.8/site-packages/pandas/io/formats/html.py',
E       -  '/usr/lib64/python3.8/site-packages/pandas/tests/indexes/multi/test_sorting.py',
E       -  '/usr/lib64/python3.8/site-packages/pandas/tests/indexing/test_loc.py',
E       -  '/usr/lib64/python3.8/site-packages/pandas/tests/indexing/multiindex/test_partial.py',
E       -  '/usr/lib64/python3.8/site-packages/pandas/tests/indexing/multiindex/test_slice.py',
E       -  '/usr/lib64/python3.8/site-packages/pandas/tests/io/json/test_pandas.py',
E       -  '/usr/lib64/python3.8/test/inspect_fodder.py',
E       -  '/usr/lib64/python3.8/test/test_fstring.py']

tests/test_rtrip.py:24: AssertionError
---------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:112     calculating dump -- bad
WARNING  root:rtrip.py:139
Files not processed due to syntax errors:
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/lib2to3/tests/data/bom.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/lib2to3/tests/data/crlf.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/lib2to3/tests/data/different_encoding.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/lib2to3/tests/data/false_encoding.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/lib2to3/tests/data/py2_test_grammar.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/test/bad_coding.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/test/bad_coding2.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/test/badsyntax_3131.py
WARNING  root:rtrip.py:141     /usr/lib64/python3.8/test/badsyntax_pep3120.py
WARNING  root:rtrip.py:143
Files failed to round-trip to AST:
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/site-packages/pandas/io/formats/html.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/site-packages/pandas/tests/indexes/multi/test_sorting.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/site-packages/pandas/tests/indexing/test_loc.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/site-packages/pandas/tests/indexing/multiindex/test_partial.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/site-packages/pandas/tests/indexing/multiindex/test_slice.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/site-packages/pandas/tests/io/json/test_pandas.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/test/inspect_fodder.py
WARNING  root:rtrip.py:145     /usr/lib64/python3.8/test/test_fstring.py
============================================================================= warnings summary =============================================================================
tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/Crypto/Signature/PKCS1_PSS.py:209: DeprecationWarning: invalid escape sequence \c
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/dbus/connection.py:337: DeprecationWarning: invalid escape sequence \
    """Arrange for the given function to be called when a signal matching

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/dbus/proxies.py:307: DeprecationWarning: invalid escape sequence \
    """Arrange for the given function to be called when the given signal

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/conch/manhole.py:172: DeprecationWarning: invalid escape sequence \)
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/conch/test/test_filetransfer.py:783: DeprecationWarning: invalid escape sequence \s
    m = re.match('^\s*#define SSH_([A-Z_]+)\s+([0-9x]*)\s*$', line)

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/conch/test/test_manhole.py:315: DeprecationWarning: invalid escape sequence \.
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/internet/test/test_endpoints.py:3865: DeprecationWarning: invalid escape sequence \:
    MemoryReactor(), "tcp6:8080:backlog=12:interface=\:\:1")

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/imap4.py:6102: DeprecationWarning: invalid escape sequence \d
    _partExpr = re.compile(b'(\d+(?:\.\d+)*)\.?')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:888: DeprecationWarning: invalid escape sequence \o
    b'oo \o oo',

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:889: DeprecationWarning: invalid escape sequence \o
    b'"oo \o oo"',

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:910: DeprecationWarning: invalid escape sequence \o
    [b'oo', b'\o', b'oo'],

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:911: DeprecationWarning: invalid escape sequence \o
    [b'oo \o oo'],

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:980: DeprecationWarning: invalid escape sequence \S
    b'(FLAGS (\Seen) INTERNALDATE "17-Jul-1996 02:44:25 -0700" '

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:1013: DeprecationWarning: invalid escape sequence \o
    check(b'("oo \o")', [b'oo \o'])

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:1014: DeprecationWarning: invalid escape sequence \o
    check(b'(oo \o)', [b'oo', b'\o'])

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:1450: DeprecationWarning: invalid escape sequence \
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:1466: DeprecationWarning: invalid escape sequence \
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:4375: DeprecationWarning: invalid escape sequence \S
    c.dataReceived(b'* 1 FETCH (FLAGS (\Seen))\r\n')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:4567: DeprecationWarning: invalid escape sequence \S
    c.dataReceived(b' FLAGS (\Seen))\r\n')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:4568: DeprecationWarning: invalid escape sequence \R
    c.dataReceived(b'* 2 FETCH (FLAGS (\Recent \Seen) RFC822 {25}\r\n')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:4895: DeprecationWarning: invalid escape sequence \A
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_imap.py:5334: DeprecationWarning: invalid escape sequence \D
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/mail/test/test_smtp.py:94: DeprecationWarning: invalid escape sequence \(
    if not re.match(b'Received: From yyy.com \(\[.*\]\) by localhost;',

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/names/client.py:575: DeprecationWarning: invalid escape sequence \w
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/protocols/basic.py:121: DeprecationWarning: invalid escape sequence \d
    _LENGTH = re.compile(b'(0|[1-9]\d*)(:)')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/protocols/basic.py:123: DeprecationWarning: invalid escape sequence \d
    _LENGTH_PREFIX = re.compile(b'(0|[1-9]\d*)$')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/protocols/ftp.py:3146: DeprecationWarning: invalid escape sequence \
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/protocols/wire.py:46: DeprecationWarning: invalid escape sequence \]
    noise = b'@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ !"#$%&?'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/python/_shellcomp.py:526: DeprecationWarning: invalid escape sequence \[
    descriptionField = descr.replace("[", "\[")

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/python/_shellcomp.py:527: DeprecationWarning: invalid escape sequence \]
    descriptionField = descriptionField.replace("]", "\]")

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/python/test/test_shellcomp.py:574: DeprecationWarning: invalid escape sequence \`
    testOutput1 = b"""#compdef silly

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/python/test/test_shellcomp.py:593: DeprecationWarning: invalid escape sequence \`
    testOutput2 = b"""#compdef silly2

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/test/test_ftp.py:1610: DeprecationWarning: invalid escape sequence \
    line1 = 'drw-r--r--   2 root     other        531 Jan  9  2003 A\ B'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/test/test_ftp.py:1613: DeprecationWarning: invalid escape sequence \
    'B A -> D\ C/A B'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/test/test_paths.py:2113: DeprecationWarning: invalid escape sequence \u
    fp = filepath.FilePath(b"\u2603")

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/test/test_process.py:2438: DeprecationWarning: invalid escape sequence \w
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/test/test_sslverify.py:1486: DeprecationWarning: invalid escape sequence \.
    message='twisted\.internet\._sslverify\.*__[gs]etstate__')]

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/trial/test/test_reporter.py:226: DeprecationWarning: invalid escape sequence \)
    'hidden exception"\)$'),

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/trial/test/test_reporter.py:235: DeprecationWarning: invalid escape sequence \s
    re.compile('^\s+File .*erroneous\.py", line \d+, in go'),

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/trial/test/test_reporter.py:236: DeprecationWarning: invalid escape sequence \s
    re.compile('^\s+raise RuntimeError\(self.hiddenExceptionMsg\)'),

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/web/test/test_error.py:322: DeprecationWarning: invalid escape sequence \(
    '  R\(a\)\n'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/web/test/test_error.py:323: DeprecationWarning: invalid escape sequence \(
    '  R\(b\)\n'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/web/test/test_error.py:325: DeprecationWarning: invalid escape sequence \(
    '    raise RuntimeError\("oh noes"\)\n'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/web/test/test_error.py:340: DeprecationWarning: invalid escape sequence \(
    '    raise RuntimeError\("oh noes"\)\n'

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/twisted/web/test/test_static.py:811: DeprecationWarning: invalid escape sequence \Z
    b'multipart/byteranges; boundary="[^"]*"\Z', contentType))

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/fontTools/cffLib/specializer.py:41: DeprecationWarning: invalid escape sequence \_
    """Takes a T2CharString program list and returns list of commands.

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/fontTools/feaLib/ast.py:682: DeprecationWarning: invalid escape sequence \
    """A chained contextual positioning statement.

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/fontTools/feaLib/ast.py:740: DeprecationWarning: invalid escape sequence \
    """A chained contextual substitution statement.

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/lldb/utils/symbolication.py:162: DeprecationWarning: invalid escape sequence \s
    addr_regex = re.compile('^\s*(?P<start>0x[0-9A-Fa-f]+)\s*$')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/lldb/utils/symbolication.py:164: DeprecationWarning: invalid escape sequence \s
    '^\s*(?P<start>0x[0-9A-Fa-f]+)\s*(?P<op>[-+])\s*(?P<end>0x[0-9A-Fa-f]+)\s*$')

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/lldb/utils/symbolication.py:480: DeprecationWarning: invalid escape sequence \.
    regex_text = '^.*\.%s$' % (re.escape(identifier))

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/site-packages/lsm/_data.py:813: DeprecationWarning: invalid escape sequence \.
    """

tests/test_rtrip.py::RtripTestCase::test_convert_stdlib
  /usr/lib64/python3.8/test/test_modulefinder.py:281: DeprecationWarning: invalid escape sequence \u
    b"""\

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
FAILED tests/test_rtrip.py::RtripTestCase::test_convert_stdlib - AssertionError: Lists differ: ['/usr/lib64/python3.8/site-packages/panda[508 chars].py'] != []
===================================================== 1 failed, 52 passed, 2 skipped, 55 warnings in 109.74s (0:01:49) =====================================================
```

**Comment by berkerpeksag** [comment] 2021-02-26 22:34
Thank you for the report. I think this is pretty much a duplicate of #146. I think it's better to convert that test to a script that can be run as part of the release process since it creates too much noise for both contributors and downstream packagers. I've just retargeted #145 to implement this idea.

**Closed by berkerpeksag** 2021-02-26 22:34 UTC
